import type { ModelSettings } from "../interfaces/model.interface";
import { RYUMII_3D_MATCHER, type BoneMatcher } from "../lib/spring-bones";

export const AVATAR_V3_SETTINGS: ModelSettings = {
  bodyTracking: true,
  fingerTracking: true,
  mirror: true,
  swapSides: true,
  swapHandedness: false,
  rollStabilize: true,
  flipPalm: true,
  naturalRest: true,
  idleMotion: true,
  idleAmount: 1,
  responsiveness: 25,
  zDamp: 0.8,
  minVisibility: 0.5,
  minCutoff: 1,
  beta: 0.7,
  physics: true,
  hair: true,
  skirt: true,
  cape: true,
  hat: false,
  stiffnessScale: 1,
  gravityScale: 1,
  dragScale: 1,
  windScale: 1,
  collide: true,
  colliderScale: 1,
  rotX: 0,
  rotY: 0,
  rotZ: 0,
  posX: 0,
  posY: -3.2,
  posZ: 0,
  scale: 2.8,
  camX: 0,
  camY: 0,
  camZ: 5,
  fov: 30,
  lightingPreset: "city",
  ambientIntensity: 0.35,
  directionalIntensity: 0.6,
  environmentIntensity: 0.6,
};

export const RYUMII_3D_SETTINGS: ModelSettings = {
  bodyTracking: true,
  fingerTracking: true,
  mirror: true,
  swapSides: true,
  swapHandedness: false,
  rollStabilize: true,
  flipPalm: true,
  naturalRest: true,
  idleMotion: true,
  idleAmount: 1,
  responsiveness: 25,
  zDamp: 0.8,
  minVisibility: 0.5,
  minCutoff: 1,
  beta: 0.7,
  physics: true,
  hair: true,
  skirt: true,
  cape: true,
  hat: false,
  stiffnessScale: 1,
  gravityScale: 1,
  dragScale: 1,
  windScale: 1,
  collide: true,
  colliderScale: 1,
  rotX: 0,
  rotY: 0,
  rotZ: 0,
  posX: 0,
  posY: -1.7,
  posZ: 2.28,
  scale: 3,
  camX: 0,
  camY: 0,
  camZ: 5,
  fov: 30,
  lightingPreset: "city",
  ambientIntensity: 0,
  directionalIntensity: 0,
  environmentIntensity: 0.6,
};

export const MODEL_SETTINGS: Record<string, ModelSettings> = {
  "Avatar V3": AVATAR_V3_SETTINGS,
  "Ryumii 3D": RYUMII_3D_SETTINGS,
};

export const MODELS: Record<
  string,
  {
    url: string;
    headBoneName?: string;
    morphOverrides?: Record<string, string>;
    springBoneMatcher?: BoneMatcher;
  }
> = {
  "Ryumii 3D": {
    url: "/models/Ryumii3D.glb",
    headBoneName: undefined,
    morphOverrides: {
      eyeBlinkLeft: "eye_closed.L",
      eyeBlinkRight: "eye_closed.R",
      eyeWideLeft: "eye_suprised.L",
      eyeWideRight: "eye_suprised.R",
      eyeSquintLeft: "eye_jitome.L",
      eyeSquintRight: "eye_jitome.R",
      browInnerUp: "brow_komari",
      browOuterUpLeft: "brow_bikkuri.L",
      browOuterUpRight: "brow_bikkuri.R",
      browDownLeft: "brow_serious.L",
      browDownRight: "brow_serious.R",
      jawOpen: "mth_open",
      mouthSmileLeft: "mth_happy",
      mouthSmileRight: "mth_happy",
      mouthFrownLeft: "mth_frown",
      mouthFrownRight: "mth_frown",
      mouthPucker: "mth_U",
      mouthFunnel: "mth_O",
      cheekPuff: "extra_cheek",
      tongueOut: "mth_bero1",
    },
    springBoneMatcher: RYUMII_3D_MATCHER,
  },
  "Avatar V3": {
    url: "/models/avatar-v3.glb",
    headBoneName: "DEF-spine006",
  },
};

export const LEFT_RIGHT_PAIRS: [string, string][] = [
  ["eyeBlinkLeft", "eyeBlinkRight"],
  ["eyeLookDownLeft", "eyeLookDownRight"],
  ["eyeLookInLeft", "eyeLookInRight"],
  ["eyeLookOutLeft", "eyeLookOutRight"],
  ["eyeLookUpLeft", "eyeLookUpRight"],
  ["eyeSquintLeft", "eyeSquintRight"],
  ["eyeWideLeft", "eyeWideRight"],
  ["browDownLeft", "browDownRight"],
  ["browOuterUpLeft", "browOuterUpRight"],
  ["cheekSquintLeft", "cheekSquintRight"],
  ["mouthDimpleLeft", "mouthDimpleRight"],
  ["mouthFrownLeft", "mouthFrownRight"],
  ["mouthLowerDownLeft", "mouthLowerDownRight"],
  ["mouthPressLeft", "mouthPressRight"],
  ["mouthSmileLeft", "mouthSmileRight"],
  ["mouthStretchLeft", "mouthStretchRight"],
  ["mouthUpperUpLeft", "mouthUpperUpRight"],
  ["noseSneerLeft", "noseSneerRight"],
];
